version: '3'

services:
  relay:
    image: n0computer/iroh-relay:v0.28.1
    container_name: iroh-relay
    restart: unless-stopped
    volumes:
      - ./config.toml:/config.toml
    command: -c /config.toml
    environment:
      - RUST_LOG=debug
    ports:
      - 3340:3340
      - 3478:3478/udp
